// Generated by scripts/render-how-diagram.py -- edit that, not this.
//
// It lives in a snippet rather than inline in index.mdx because the MDX pipeline strips SVG
// <text> (and bare <strong>) from the page: the shapes survive, the labels do not. Snippets are
// real modules, so the whole drawing arrives intact.
export const HowDiagram = () => (
  <>
    <svg className="cr-diagram cr-dia-wide" viewBox="0 0 1200 418" role="img"
      aria-labelledby="cr-dia-t cr-dia-d" preserveAspectRatio="xMidYMid meet">
      <title id="cr-dia-t">How ctrlrun works</title>
      <desc id="cr-dia-d">An action leaves the agents, tools and workflows you already run. Inside ctrlrun it is normalized into one action, decided against your rules, held for approval, reserved so it cannot run twice, executed, resolved and recorded. Only then does it reach your systems. An action with no rule is blocked, changed arguments void the approval, and an unknown outcome is never retried.</desc>
      <rect className="cr-dia-strip" x="1" y="1" width="1198" height="54" rx="6" />
      <text className="cr-dia-label" x="24" y="33">YOUR AGENTS, TOOLS AND WORKFLOWS</text>
      <text className="cr-dia-claim" x="390" y="34">An action is about to run.</text>
      <text className="cr-dia-note" x="628" y="34">Any model, any framework. Existing code stays as it is.</text>
      <path className="cr-dia-arrow" d="M600 56V83" />
      <path className="cr-dia-head" d="M595 82h10L600 90Z" />
      <rect className="cr-dia-box" x="1" y="92" width="1198" height="230" rx="6" />
      <text className="cr-dia-label" x="24" y="122">ctrlrun · THE EXECUTION BOUNDARY</text>
      <rect className="cr-dia-node" x="24" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="37" y="162">1</text>
      <text className="cr-dia-name" x="37" y="186">Normalize</text>
      <text className="cr-dia-gloss" x="37" y="206">one action, one id</text>
      <path className="cr-dia-arrow" d="M173 181h11" />
      <path className="cr-dia-head" d="M183 176.5l7 4.5-7 4.5Z" />
      <rect className="cr-dia-node" x="192" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="205" y="162">2</text>
      <text className="cr-dia-name" x="205" y="186">Decide</text>
      <text className="cr-dia-gloss" x="205" y="206">allow / ask / block</text>
      <path className="cr-dia-arrow" d="M341 181h11" />
      <path className="cr-dia-head" d="M351 176.5l7 4.5-7 4.5Z" />
      <rect className="cr-dia-node" x="360" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="373" y="162">3</text>
      <text className="cr-dia-name" x="373" y="186">Approve</text>
      <text className="cr-dia-gloss" x="373" y="206">bound to this action</text>
      <path className="cr-dia-arrow" d="M509 181h11" />
      <path className="cr-dia-head" d="M519 176.5l7 4.5-7 4.5Z" />
      <rect className="cr-dia-node" x="528" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="541" y="162">4</text>
      <text className="cr-dia-name" x="541" y="186">Reserve</text>
      <text className="cr-dia-gloss" x="541" y="206">claimed once</text>
      <path className="cr-dia-arrow" d="M677 181h11" />
      <path className="cr-dia-head" d="M687 176.5l7 4.5-7 4.5Z" />
      <rect className="cr-dia-node" x="696" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="709" y="162">5</text>
      <text className="cr-dia-name" x="709" y="186">Execute</text>
      <text className="cr-dia-gloss" x="709" y="206">your code runs</text>
      <path className="cr-dia-arrow" d="M845 181h11" />
      <path className="cr-dia-head" d="M855 176.5l7 4.5-7 4.5Z" />
      <rect className="cr-dia-node" x="864" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="877" y="162">6</text>
      <text className="cr-dia-name" x="877" y="186">Resolve</text>
      <text className="cr-dia-gloss" x="877" y="206">unknown is not failed</text>
      <path className="cr-dia-arrow" d="M1013 181h11" />
      <path className="cr-dia-head" d="M1023 176.5l7 4.5-7 4.5Z" />
      <rect className="cr-dia-node" x="1032" y="138" width="144" height="86" rx="5" />
      <text className="cr-dia-num" x="1045" y="162">7</text>
      <text className="cr-dia-name" x="1045" y="186">Record</text>
      <text className="cr-dia-gloss" x="1045" y="206">a receipt either way</text>
      <path className="cr-dia-div" d="M24 252H1176" />
      <text className="cr-dia-rule" x="24" y="278">No rule for it</text>
      <text className="cr-dia-rule-note" x="24" y="298">The action is blocked. Silence is never permission.</text>
      <text className="cr-dia-rule" x="418" y="278">Arguments changed after sign-off</text>
      <text className="cr-dia-rule-note" x="418" y="298">The old approval is void. A person signs again.</text>
      <text className="cr-dia-rule" x="812" y="278">Outcome unknown</text>
      <text className="cr-dia-rule-note" x="812" y="298">No retry until a person resolves it. Nothing runs twice on a guess.</text>
      <path className="cr-dia-arrow" d="M600 324V353" />
      <path className="cr-dia-head" d="M595 352h10L600 360Z" />
      <rect className="cr-dia-strip" x="1" y="362" width="1198" height="54" rx="6" />
      <text className="cr-dia-label" x="24" y="394">YOUR SYSTEMS</text>
      <text className="cr-dia-claim" x="252" y="395">The action arrives already checked.</text>
      <text className="cr-dia-note" x="560" y="395">Allowed by your rules, approved where you require it, and never run twice.</text>
    </svg>
    <svg className="cr-diagram cr-dia-narrow" viewBox="0 0 360 748" role="img"
      aria-labelledby="cr-dia-tn cr-dia-dn" preserveAspectRatio="xMidYMid meet">
      <title id="cr-dia-tn">How ctrlrun works</title>
      <desc id="cr-dia-dn">An action leaves the agents, tools and workflows you already run. Inside ctrlrun it is normalized into one action, decided against your rules, held for approval, reserved so it cannot run twice, executed, resolved and recorded. Only then does it reach your systems. An action with no rule is blocked, changed arguments void the approval, and an unknown outcome is never retried.</desc>
      <rect className="cr-dia-strip" x="1" y="1" width="358" height="76" rx="6" />
      <text className="cr-dia-label" x="16" y="25">YOUR AGENTS, TOOLS AND WORKFLOWS</text>
      <text className="cr-dia-claim" x="16" y="47">An action is about to run.</text>
      <text className="cr-dia-note" x="16" y="66">Any model, any framework. Existing code stays as it is.</text>
      <path className="cr-dia-arrow" d="M180 78V95" />
      <path className="cr-dia-head" d="M175 94h10L180 102Z" />
      <rect className="cr-dia-box" x="1" y="104" width="358" height="536" rx="6" />
      <text className="cr-dia-label" x="16" y="130">ctrlrun · THE EXECUTION BOUNDARY</text>
      <path className="cr-dia-spine" d="M28 150V420" />
      <rect className="cr-dia-node" x="28" y="142" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="164">1</text>
      <text className="cr-dia-name" x="58" y="164">Normalize</text>
      <text className="cr-dia-gloss" x="156" y="164">one action, one id</text>
      <rect className="cr-dia-node" x="28" y="184" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="206">2</text>
      <text className="cr-dia-name" x="58" y="206">Decide</text>
      <text className="cr-dia-gloss" x="156" y="206">allow / ask / block</text>
      <rect className="cr-dia-node" x="28" y="226" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="248">3</text>
      <text className="cr-dia-name" x="58" y="248">Approve</text>
      <text className="cr-dia-gloss" x="156" y="248">bound to this action</text>
      <rect className="cr-dia-node" x="28" y="268" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="290">4</text>
      <text className="cr-dia-name" x="58" y="290">Reserve</text>
      <text className="cr-dia-gloss" x="156" y="290">claimed once</text>
      <rect className="cr-dia-node" x="28" y="310" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="332">5</text>
      <text className="cr-dia-name" x="58" y="332">Execute</text>
      <text className="cr-dia-gloss" x="156" y="332">your code runs</text>
      <rect className="cr-dia-node" x="28" y="352" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="374">6</text>
      <text className="cr-dia-name" x="58" y="374">Resolve</text>
      <text className="cr-dia-gloss" x="156" y="374">unknown is not failed</text>
      <rect className="cr-dia-node" x="28" y="394" width="316" height="34" rx="4" />
      <text className="cr-dia-num" x="40" y="416">7</text>
      <text className="cr-dia-name" x="58" y="416">Record</text>
      <text className="cr-dia-gloss" x="156" y="416">a receipt either way</text>
      <path className="cr-dia-div" d="M28 446H344" />
      <text className="cr-dia-rule" x="28" y="470">No rule for it</text>
      <text className="cr-dia-rule-note" x="28" y="488">The action is blocked.</text>
      <text className="cr-dia-rule-note" x="28" y="504">Silence is never permission.</text>
      <text className="cr-dia-rule" x="28" y="534">Arguments changed after sign-off</text>
      <text className="cr-dia-rule-note" x="28" y="552">The old approval is void.</text>
      <text className="cr-dia-rule-note" x="28" y="568">A person signs again.</text>
      <text className="cr-dia-rule" x="28" y="598">Outcome unknown</text>
      <text className="cr-dia-rule-note" x="28" y="616">No retry until a person resolves it.</text>
      <text className="cr-dia-rule-note" x="28" y="632">Nothing runs twice on a guess.</text>
      <path className="cr-dia-arrow" d="M180 642V661" />
      <path className="cr-dia-head" d="M175 660h10L180 668Z" />
      <rect className="cr-dia-strip" x="1" y="670" width="358" height="76" rx="6" />
      <text className="cr-dia-label" x="16" y="694">YOUR SYSTEMS</text>
      <text className="cr-dia-claim" x="16" y="716">The action arrives already checked.</text>
      <text className="cr-dia-note" x="16" y="735">Allowed by your rules, approved where you require it.</text>
    </svg>
  </>
);
