"""What the README claims, and what the adapter page records, against the library itself.

These four checks came out of the library's `test_packaging.py` when the documentation moved.
They were never about packaging: `CLAIMS.md` maps every README sentence to the code and the
test that prove it, and `adapters.md` records the questions a third adapter could not answer
from the contract alone. Both are pages, so both are here -- and what they are checked against
is the library, read from `CORE_ROOT`.

**Each of them used to carry a `pytest.skip("no repository checkout")` on a missing page.**
That guard was written for an sdist, where the pages were pruned; after the split it would
have read every one of these as "nothing to check" and gone green. There is no skip here. A
page that is missing is a failure, and `_core.py` makes a missing library one too.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

from _core import CORE_ROOT

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS = REPO_ROOT / "tools" / "docs_audit"


def _readme() -> str:
    return (CORE_ROOT / "README.md").read_text(encoding="utf-8")


CLAIM_WORDS = ("conformant", "compliant", "certified", "aligned with")


NEGATORS = ("not ", "no ", "never", "cannot", "n't", "without")


def _claims(text: str) -> list[str]:
    """Sentences using a claim word **affirmatively**."""

    offending = []
    for sentence in re.split(r"(?<=[.!?])\s+|\n\n", text):
        lowered = sentence.lower()
        if any(word in lowered for word in CLAIM_WORDS) and not any(
            negator in lowered for negator in NEGATORS
        ):
            offending.append(sentence.strip())
    return offending


def test_every_test_docs_claims_cites_exists():
    """`docs/CLAIMS.md` maps every README sentence to the test that proves it, and a citation
    naming a test that does not exist is the same false claim the file exists to prevent.

    It has been regenerated by hand at three releases now, and the names drift: a test gets
    renamed, the row keeps the old one, and the table reads as evidence while pointing at
    nothing. This is cheap and it is the only thing standing between the two.
    """

    claims = REPO_ROOT / "docs" / "CLAIMS.md"
    cited = set(re.findall(r"`(test_[A-Za-z0-9_]+)`", claims.read_text(encoding="utf-8")))
    defined: set[str] = set()
    for path in [*(CORE_ROOT / "tests").glob("*.py"), *(REPO_ROOT / "tests").glob("*.py")]:
        defined.update(re.findall(r"^def (test_[A-Za-z0-9_]+)", path.read_text(), re.M))

    assert cited, "CLAIMS.md cites no tests at all, which is not a table of evidence"
    assert not cited - defined, (
        f"CLAIMS.md cites tests that do not exist: {sorted(cited - defined)}"
    )


def test_T139_docs_adapters_exists_and_leads_with_the_three_ways_in():
    path = REPO_ROOT / "docs" / "adapters.md"
    text = path.read_text(encoding="utf-8")

    assert "You probably do not need one" in text
    assert "@protect" in text and "gateway" in text
    # Item 6's list is the evidence the contract was read by somebody who could not read the code.
    assert "§12.10" in text
    assert _claims(text) == []


def test_the_claims_table_line_numbers_point_at_what_they_name():
    """The claims page says *"Line numbers refer to that tag"*, and until this test they did not:
    seven of twenty-nine resolvable references had drifted by the time v0.5 was cut, pointing at
    a string literal, a comment, or the middle of another function.

    A claims table is evidence, and a reference that lands on the wrong line is the same failure
    as a cited test that does not exist -- which the test below this one has caught since v0.4.
    Both are cheap and both are the only thing standing between the table and rot.

    Only references whose cell **names** a symbol are checked, since those are the ones that can
    be resolved mechanically. A drifted line for a reference with no symbol is not caught here,
    which is stated rather than left to be assumed.
    """

    claims = REPO_ROOT / "docs" / "CLAIMS.md"
    if not claims.exists():  # pragma: no cover - not a checkout
        pytest.skip("no repository checkout")

    text = claims.read_text(encoding="utf-8")
    # `cli/main.py:400` as well as `state.py:400`. The first version's `[a-z_]+\.py` matched no
    # path with a directory in it, so **every** `cli/main.py` reference was invisible to this
    # guard -- and a review found two of them stale, one broken by the commit that added this
    # very check to the rows beside it. A guard that cannot see a whole class of reference is
    # attribution dressed as prevention.

    sys.path.insert(0, str(TOOLS))
    from claims import citations

    # **One producer for "which symbol is this citation about".** `scripts/repoint-claims.py`
    # writes these numbers and this checks them, and they used to answer that question
    # separately: both collected the symbols of the whole *row*. So a row citing six commands
    # had every reference re-pointed at one definition, and this guard accepted all six,
    # because that line does define a symbol the row names. A row claiming to cite six
    # commands cited one, six times, and the check said it was fine.
    stale = []
    checked = 0
    for row in text.splitlines():
        for cited in citations(row):
            if not cited.names:
                stale.append(f"{cited.filename}:{cited.line} cites code and names no symbol")
                continue
            source = CORE_ROOT / "src" / "ctrlrun" / cited.filename
            if not source.exists():
                continue
            lines = source.read_text(encoding="utf-8").splitlines()
            line = lines[cited.line - 1] if 0 < cited.line <= len(lines) else ""
            checked += 1

            # **Whole words, not substrings**, and this citation's own symbols first. A
            # definition would be the strict rule and it is too strict: rows here legitimately
            # cite a statement rather than a `def` -- `effect_key TEXT PRIMARY KEY` inside a
            # DDL string, the branch where only `NotExecuted` maps to `FAILED`. The row's
            # symbols are the documented fallback, because assigning each symbol to its nearest
            # citation is a heuristic; a line matching neither is stale whichever way they were
            # assigned, which is the case worth catching.
            #
            # The residual, stated: a named symbol appearing as a whole word *in prose* still
            # satisfies this.
            def names_on(line: str, names: tuple[str, ...]) -> bool:
                return any(re.search(rf"\b{re.escape(name)}\b", line) for name in names)

            if not names_on(line, cited.local) and not names_on(line, cited.names):
                stale.append(
                    f"{cited.filename}:{cited.line} is {line.strip()[:60]!r}, "
                    f"names {list(cited.local) or list(cited.names)}"
                )

    assert checked, "CLAIMS.md cites no code locations at all"
    assert stale == [], stale


def test_T138_item_sixs_questions_are_recorded_and_each_is_answered():
    """SPEC-v0.5 §8 T138: a third adapter was written against the contract alone, and **the list
    of questions it could not answer is the deliverable**, recorded in `docs/adapters.md` with
    each answered by an edit to `SPEC-v0.5.md`.

    *"If the list cannot be emptied, v0.5 is not done."* So this asserts the list exists, that
    every entry names where it was answered, and that the sections it names are real. The
    adapter itself is disposable and is deliberately not in the repository — asserting its
    existence would be asserting the wrong half.

    This test was missing when v0.5 was otherwise complete, and `docs/adapters.md` carried a
    summary of the list rather than the list. A summary cannot be checked against the spec.
    """
    adapters = REPO_ROOT / "docs" / "adapters.md"
    spec = CORE_ROOT / "docs" / "SPEC-v0.5.md"

    text = adapters.read_text(encoding="utf-8")
    # The answer column is `(.*?)` and not `(.+?)` on purpose: an **empty** answer must still
    # match, so the "every row says where it was answered" check below is what catches it. With
    # `(.+?)` the row simply stopped being a row and the count assertion caught it instead --
    # a subsumed guard, found by mutating an answer to empty and watching the wrong test fail.
    rows = re.findall(r"^\| (Q\d+) \| (.+?) \| (.+?) \|(.*?)\|$", text, re.M)

    assert len(rows) >= 14, f"item 6 raised fourteen questions; {len(rows)} are recorded"
    assert [q for q, *_ in rows] == [f"Q{n}" for n in range(1, len(rows) + 1)], [
        q for q, *_ in rows
    ]

    # Every row says where it was answered, and every section it names exists in the spec.
    spec_text = spec.read_text(encoding="utf-8")
    unanswered = [q for q, _, _, answer in rows if not answer.strip()]
    assert unanswered == [], unanswered

    cited = {
        section for _, _, _, answer in rows for section in re.findall(r"§(\d+(?:\.\d+)*)", answer)
    }
    assert cited, "no row names a section of SPEC-v0.5"
    missing = [
        s for s in sorted(cited) if f"### {s} " not in spec_text and f"## {s}. " not in spec_text
    ]
    assert missing == [], f"rows cite sections that do not exist: {missing}"

    # The four the report called security- or correctness-critical are marked as such.
    severities = {severity.strip().strip("*").lower() for _, _, severity, _ in rows}
    assert "security" in severities, severities
