"""Render `docs/reference/cli.mdx` from click's own help text, and refuse a copy that drifted.

The CLI reference is `ctrlrun --help` and every subcommand's `--help`, verbatim, so the page
cannot say something the command does not. Edit a command's docstring or option help in
`src/ctrlrun/cli/main.py`; never this page.

    python tools/docs_audit/render_cli.py --write
    python tools/docs_audit/render_cli.py --check

Help text wraps to the terminal width, so the width is pinned here: the page is the same on a
laptop and in CI.
"""

from __future__ import annotations

import argparse
import os
import sys

from _files import REPO_ROOT, relative

TARGET = REPO_ROOT / "docs" / "reference" / "cli.mdx"
COLUMNS = "88"
MARKER = "generated by tools/docs_audit/render_cli.py from click's help text — edit the command docstrings, never this page"


def help_texts() -> list[tuple[str, str]]:
    """`(command name, help text)` for `ctrlrun` and every subcommand, in registration order."""
    os.environ["COLUMNS"] = COLUMNS
    from click.testing import CliRunner

    from ctrlrun.cli.main import main

    runner = CliRunner()
    texts = [("ctrlrun", runner.invoke(main, ["--help"], env={"COLUMNS": COLUMNS}).output)]
    for name in main.commands:
        result = runner.invoke(main, [name, "--help"], env={"COLUMNS": COLUMNS})
        texts.append((f"ctrlrun {name}", result.output))
    return texts


def render() -> str:
    lines = [
        "---",
        'title: "CLI reference"',
        'description: "Every ctrlrun command and option, from the command\'s own help text: init, demo, approve, deny, receipts, effects, resolve, inspect, stats, verify, delegate, revoke and gateway."',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
        "The `ctrlrun` command reads the policy in the working directory (`ctrlrun.yaml`, or the",
        "file `$CTRLRUN_CONFIG` names) and the store beside it, `.ctrlrun/state.db`, unless",
        "`--store-url` or `$CTRLRUN_STORE_URL` names another. A command that reads evidence creates",
        "nothing and migrates nothing. Each section below is the command's own `--help`, verbatim.",
        "",
    ]
    for name, text in help_texts():
        lines.append(f"## {name}")
        lines.append("")
        lines.append("```text")
        lines.append(text.rstrip("\n"))
        lines.append("```")
        lines.append("")
    lines += [
        "## Next",
        "",
        "- [Exit codes](/reference/exit-codes): what each command's exit status means.",
        "- [Resolve an AMBIGUOUS effect](/guides/resolve-an-ambiguous-effect): `effects`, `resolve` and `inspect` in use.",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    text = render()
    if arguments.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text, encoding="utf-8")
        print(f"wrote {relative(TARGET)}")
    if arguments.check or not arguments.write:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"DRIFT {relative(TARGET)} differs from click's help text; run --write")
            return 1
        print(f"cli reference: {relative(TARGET)} matches")
    return 0


if __name__ == "__main__":
    sys.exit(main())
