"""Render the readiness block, the same in three places, from generated sources only.

The block is the first thing a stranger reads about whether CTRLRun can be run for real, so
every number in it comes from something that measures itself:

- the version and the dependency floor from `pyproject.toml`;
- the Python floor from `requires-python`, and the Pythons tested from CI's `check` matrix;
- the test count from `pytest --collect-only`, recorded in `generated/readiness.json`;
- the soak's duration, actions and unattributed count from `research/soak/results/*.json`;
- what `ctrlrun verify` checks from the guarantee catalogue itself.

And it carries a **Not yet** list, inside the block and never below it: no external security
audit, no third-party review of the kernel, no sector packs. The honest half is why the first
half is believed. A line leaves only when the thing it names has become true, in its own pull
request, and `docs/CLAIMS.md` changes in the same one.

    python tools/docs_audit/render_readiness.py --write   # refresh, re-counting the suite
    python tools/docs_audit/render_readiness.py --check    # what CI runs

**The test count is a floor, not a snapshot.** `--check` fails when the suite has *fewer* tests
than the block claims, and passes when it has more: the suite only grows, and a number that had
to be regenerated by every pull request that added a test would be regenerated without being
read. `--write` records the count of the moment; the badge in the README is live.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

import yaml

from _core import CORE_ROOT
from _files import REPO_ROOT, relative

STATE = REPO_ROOT / "generated" / "readiness.json"
GENERATED = REPO_ROOT / "generated"
FILENAMES = {"readme": "readiness.readme.md", "mdx": "readiness.mdx", "full": "readiness.full.mdx"}
FORMATS = tuple(FILENAMES)
SOAK = CORE_ROOT / "research" / "soak" / "results"
_OPEN = re.compile(r"generated from the suite, pyproject and the soak \((?P<format>[a-z]+)\)")
_CLOSE = re.compile(r"end generated")

#: Stated here rather than counted, because each is a statement about what has **not** been
#: done and nothing in the repository can measure an absence. Removing one is its own pull
#: request, with the CLAIMS.md row that makes the new sentence true.
NOT_YET: tuple[tuple[str, str], ...] = (
    ("No external security audit.", "optional, and no release waits for one"),
    ("No third-party review of the kernel.", "every review so far was run inside this project"),
    ("No sector packs.", "the policy templates are starting points, not a product"),
)


def _version() -> str:
    with (CORE_ROOT / "pyproject.toml").open("rb") as handle:
        return str(tomllib.load(handle)["project"]["version"])


def _python() -> dict:
    """The Python floor the package declares, and the Pythons CI's `check` job runs the suite on.

    The block said *"Python 3.11 and later"* as a literal, which stays true when CI adds a
    version and so never drifted into a failure. The tested list is read from the matrix rather
    than the classifiers because the matrix is what runs the suite; a classifier is a label.
    """
    with (CORE_ROOT / "pyproject.toml").open("rb") as handle:
        requires = str(tomllib.load(handle)["project"]["requires-python"])
    if not re.fullmatch(r">=3\.\d+", requires):
        raise SystemExit(f"requires-python is {requires!r}; the block can only state a >=3.N floor")
    workflow = CORE_ROOT / ".github" / "workflows" / "ci.yml"
    matrix = yaml.safe_load(workflow.read_text(encoding="utf-8"))["jobs"]["check"]["strategy"]
    tested = matrix["matrix"]["python-version"]
    # Unquoted in YAML, `3.10` is the float 3.1. Refused rather than repaired.
    if not all(isinstance(version, str) for version in tested):
        raise SystemExit(f"CI's python-version matrix must be quoted strings, got {tested!r}")
    floor = requires.removeprefix(">=")
    if floor not in tested:
        raise SystemExit(f"requires-python is {requires} and CI's check job does not test {floor}")
    return {"floor": floor, "tested": sorted(tested, key=lambda v: tuple(map(int, v.split("."))))}


def _tested(versions: list[str]) -> str:
    """`3.11 to 3.14` for a contiguous run of minors, `3.11, 3.12 and 3.14` otherwise."""
    minors = [int(version.split(".")[1]) for version in versions]
    if len(versions) > 2 and minors == list(range(minors[0], minors[-1] + 1)):
        return f"{versions[0]} to {versions[-1]}"
    return versions[0] if len(versions) == 1 else f"{', '.join(versions[:-1])} and {versions[-1]}"


#: A changelog heading: `## [0.6.0] - unreleased — Durable runtime`, or with a date. The file
#: uses a hyphen and an em dash interchangeably as the separator, so both are accepted.
_HEADING = re.compile(r"^## \[(?P<version>[^\]]+)\]\s*[-—]\s*(?P<when>[^\s—]+)", re.M)


def released() -> str | None:
    """The newest version the changelog gives a date to, or `None` if it gives none.

    The readiness block used to say *"Version 0.6.0, on PyPI"* off `pyproject.toml` alone, and
    on the day it was written 0.6.0 was `unreleased` and PyPI held 0.5.0 — a false sentence on
    the README, produced by a generator, which is the failure a generator is supposed to make
    impossible. The changelog is the source because it is the file that already has to be
    right before a tag, and it flips this line on its own when the release lands.
    """
    text = (CORE_ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    for found in _HEADING.finditer(text):
        if found.group("when").lower() != "unreleased":
            return found.group("version")
    return None


def _collected_in(root: Path) -> int:
    """How many tests `pytest` collects in one checkout."""
    result = subprocess.run(
        # `-o addopts=` discards whatever the checkout's own pytest configuration adds.
        # This repository's sets `-q`, which on top of the `-q` below is `-qq` -- and at two
        # levels of quiet pytest stops printing "N tests collected" at all and prints a count
        # per file instead. The counter would then have been reading a format that depends on
        # the configuration of the tree it happens to be pointed at.
        [
            sys.executable,
            "-m",
            "pytest",
            "--collect-only",
            "-q",
            "-o",
            "addopts=",
            "-p",
            "no:cacheprovider",
        ],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    found = re.search(r"(\d+)\s+tests? collected", result.stdout)
    if found is None:
        raise SystemExit(
            f"could not read a test count from pytest in {root}:\n{result.stdout[-2000:]}"
        )
    return int(found.group(1))


def collected() -> int:
    """How many tests `pytest` collects right now, across **both** checkouts.

    The number is published in the readiness block and on the test-count badge, and what it
    has always meant is "the size of the suite standing behind these guarantees". The split
    put that suite in two repositories and did not make it smaller, so counting one of them
    would drop roughly a third of it and report a shrunken suite as the truth.

    The library first, because it is the larger half and because a failure there is the more
    urgent one to name. Both are counted the same way -- what `pytest` **collects**, which is
    not what passed; the badge is labelled `tests` and carries a count for that reason.
    """
    return _collected_in(CORE_ROOT) + _collected_in(REPO_ROOT)


def soak() -> dict | None:
    """The most recent soak run, or `None` where none has been published."""
    files = sorted(SOAK.glob("*.json")) if SOAK.is_dir() else []
    return json.loads(files[-1].read_text(encoding="utf-8")) if files else None


def state() -> dict:
    return json.loads(STATE.read_text(encoding="utf-8")) if STATE.exists() else {}


def measure() -> dict:
    """Everything the block says, measured now."""
    run = soak()
    return {
        "version": _version(),
        "python": _python(),
        "released": released(),
        "tests": collected(),
        "guarantees": _guarantees(),
        "soak": None
        if run is None
        else {
            "elapsed": run["elapsed_human"],
            "elapsed_seconds": run["elapsed_seconds"],
            "backend": run["backend"].split(" ")[0],
            "actions": run["actions"],
            "unexplained": run["unexplained"],
            "positive_control": run["positive_control_fired"],
        },
    }


def _guarantees() -> int:
    from ctrlrun.verify.guarantees import GUARANTEES

    return len(GUARANTEES)


def _lines(data: dict, *, full: bool) -> list[str]:
    version, tests, guarantees = data["version"], data["tests"], data["guarantees"]
    run, published = data["soak"], data.get("released")
    link = "https://pypi.org/project/ctrlrun/"
    python = f"Python {data['python']['floor']} and later, tested on {_tested(data['python']['tested'])}."

    def where(text: str, page: str) -> str:
        """`full` adds a Read-more link; the other formats carry the sentence alone.

        The soak line is the exception and links in every format: on the README and the docs
        home it is the one bullet a reader could quote as a stronger claim than it is, so the
        route to the page that qualifies it travels with it.
        """
        if full:
            return f"{text} [Read more](/docs/{page})."
        if page == "production/soak":
            return f"{text} [What it does not establish](https://ctrlrun.dev/docs/{page})."
        return text

    lines = [
        (
            f"- **Version {version}**, on [PyPI]({link}), {python}"
            if published == version
            else f"- **Version {version} is in development**; [PyPI]({link}) has {published}. "
            + python
        ),
        where(
            f"- **{tests:,} tests**, every version specified before it was written and every "
            "requirement mutation-tested.",
            "how-this-is-built",
        ),
        where(
            f"- **{guarantees} guarantees you can check in your own setup**, with `ctrlrun verify` "
            "against your policy, on your store's backend, in a scratch store it creates.",
            "security/verify-guarantees",
        ),
        where(
            "- **One host: a file.** SQLite, no server, no ops. **Many hosts: Postgres**, the same "
            "guarantees, graded by the same suite.",
            "production/postgres",
        ),
    ]
    if run is not None:
        lines.append(
            where(
                f"- **Soaked for {run['elapsed']} on {run['backend']}**: {run['actions']:,} actions, "
                f"{run['unexplained']} unattributed ambiguous outcomes"
                + (", positive control fired." if run["positive_control"] else ".")
                # The duration travels with the number, in every format. Without it the README
                # and the docs home carried "soaked" with no route to the page that says what
                # a run of that length cannot show -- the flattering half of a true sentence,
                # on the two surfaces most likely to be quoted. SPEC-v0.6 §8.1 took the
                # duration out of the *criterion* and not out of this line: the gate went, the
                # fact did not, and the link goes to the page that separates them.
                + " Nothing here establishes what only accumulates over days.",
                "production/soak",
            )
        )
    else:
        lines.append("- **The soak has not been run for this version yet.**")
    lines += [
        where(
            "- **Each receipt carries the hash of the one before it**, so an alteration is detected "
            "and named.",
            "production/receipt-integrity",
        ),
        "- **Apache-2.0**, and the enforcement kernel stays open source. Releases carry PyPI "
        "provenance attestations from GitHub Actions.",
        "",
        "**Not yet:**",
        "",
    ]
    lines += [f"- {claim} ({why})" for claim, why in NOT_YET]
    return lines


def render(fmt: str, data: dict) -> str:
    body = _lines(data, full=fmt == "full")
    comment = f"generated from the suite, pyproject and the soak ({fmt}) — run the generator"
    open_marker = f"<!-- {comment} -->" if fmt == "readme" else "{/* " + comment + " */}"
    close_marker = "<!-- end generated -->" if fmt == "readme" else "{/* end generated */}"
    return "\n".join([open_marker, *body, close_marker]) + "\n"


def marker_blocks(text: str) -> list[tuple[int, str, str]]:
    lines = text.splitlines()
    blocks: list[tuple[int, str, str]] = []
    index = 0
    while index < len(lines):
        opened = _OPEN.search(lines[index])
        if opened is None:
            index += 1
            continue
        start, fmt = index, opened.group("format")
        index += 1
        while index < len(lines) and not _CLOSE.search(lines[index]):
            index += 1
        if index >= len(lines):
            blocks.append((start + 1, fmt, ""))
            break
        blocks.append((start + 1, fmt, "\n".join(lines[start : index + 1]) + "\n"))
        index += 1
    return blocks


def check(data: dict, pages: list[Path] | None = None) -> list[str]:
    drift: list[str] = []
    recorded = state()
    if not recorded:
        return [f"{relative(STATE)} is missing; run --write"]
    current = data["tests"]
    if current < recorded["tests"]:
        drift.append(
            f"the block claims {recorded['tests']:,} tests and the suite collects {current:,}; "
            "run --write"
        )
    for key in ("version", "python", "released", "guarantees", "soak"):
        if recorded.get(key) != data.get(key):
            drift.append(f"{key} changed since the block was generated; run --write")
    for fmt in FORMATS:
        target = GENERATED / FILENAMES[fmt]
        expected = render(fmt, recorded)
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            drift.append(f"{relative(target)} differs from the generator; run --write")
    if pages is None:
        from _files import documents

        # **Root-level pages too.** `docs.mdx` is the docs home and carries two marker blocks,
        # and a glob of `docs/**` does not reach a file called `docs.mdx` beside that directory:
        # its capability grid and its readiness block went unchecked, and the readiness one sat
        # at version 0.8.0 with a stale guarantee count through a whole milestone. `*.md` and
        # `*.mdx` are already in `SITE_PATTERNS` for exactly this reason.
        pages = documents(patterns=("README.md", "*.md", "*.mdx", "docs/**/*.md", "docs/**/*.mdx"))
    for page in pages:
        if page.parent == GENERATED:
            continue
        for line, fmt, embedded in marker_blocks(page.read_text(encoding="utf-8")):
            if fmt not in FORMATS:
                drift.append(f"{relative(page)}:{line}: unknown readiness format {fmt!r}")
            elif embedded != render(fmt, recorded):
                drift.append(f"{relative(page)}:{line}: readiness block differs; paste it fresh")
    return drift


def write(data: dict) -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    for fmt in FORMATS:
        (GENERATED / FILENAMES[fmt]).write_text(render(fmt, data), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("format", nargs="?", choices=FORMATS)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    if arguments.format:
        sys.stdout.write(render(arguments.format, state() or measure()))
        return 0
    data = measure()
    if arguments.write:
        write(data)
        print(f"readiness: {data['tests']:,} tests, version {data['version']}, written")
    if arguments.check or not arguments.write:
        drift = check(data)
        for item in drift:
            print(f"DRIFT {item}")
        print(f"readiness: {len(drift)} drifted")
        return 0 if not drift else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
