"""Render the Python API reference from docstrings, one page per frozen public name.

`docs/IA.md`, decision (b): Mintlify has no native docstring reference, so griffe loads the
package statically (no import, so the lazy extras render without their dependencies), parses
Google-style docstrings, and this script emits MDX under `docs/reference/api/` plus the index
page and the *Python API* group of `docs.json`. `--check` refuses any of them that drifted.

    python tools/docs_audit/render_api.py --write
    python tools/docs_audit/render_api.py --check

The names come from `ctrlrun.__all__` (frozen by the specifications' public-name sections)
plus the entry points of the extras and of verify, listed in `EXTRA_NAMES`.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterable
from pathlib import Path

from _files import REPO_ROOT, relative

API_DIR = REPO_ROOT / "docs" / "reference" / "api"
DOCS_JSON = REPO_ROOT / "docs" / "docs.json"
GROUP = "Python API"
MARKER = "generated by tools/docs_audit/render_api.py from the docstrings — edit the docstring, never this page"

#: Public names that live behind an extra or above the kernel and are not in `ctrlrun.__all__`.
EXTRA_NAMES: tuple[tuple[str, str], ...] = (
    ("ctrlrun.postgres", "PostgresStateStore"),
    ("ctrlrun.otel", "OTelEventSink"),
    ("ctrlrun.jwt_identity", "JWTIdentityProvider"),
    ("ctrlrun.acs", "AcsControlHook"),
    ("ctrlrun.gateway", "serve"),
    ("ctrlrun.verify", "run"),
    ("ctrlrun.conformance", "run"),
    ("ctrlrun.conformance.store", "run"),
)


def _load():  # noqa: ANN202 - griffe's types are the return value
    import griffe

    return griffe.load("ctrlrun", search_paths=[str(REPO_ROOT / "src")], docstring_parser="google")


def _public_names(package) -> list[tuple[str, str]]:  # noqa: ANN001
    from ctrlrun import __all__

    names = [("ctrlrun", name) for name in __all__]
    names += list(EXTRA_NAMES)
    return names


def _resolve(package, module_path: str, name: str):  # noqa: ANN001, ANN202
    module = package
    for part in module_path.split(".")[1:]:
        module = module.members[part]
    member = module.members[name]
    while getattr(member, "is_alias", False):
        try:
            member = member.final_target
        except Exception:
            break
    return member


def _slug(module_path: str, name: str) -> str:
    if module_path == "ctrlrun":
        return name
    return module_path.removeprefix("ctrlrun.").replace(".", "-") + "-" + name


def _kind(member) -> str:  # noqa: ANN001
    return str(member.kind.value) if hasattr(member.kind, "value") else str(member.kind)


def _signature(member) -> str:  # noqa: ANN001
    kind = _kind(member)
    if kind == "function":
        params = ", ".join(
            str(p.name) if p.annotation is None else f"{p.name}: {p.annotation}"
            for p in member.parameters
        )
        returns = f" -> {member.returns}" if member.returns is not None else ""
        return f"def {member.name}({params}){returns}"
    if kind == "class":
        bases = ", ".join(str(b) for b in member.bases)
        init = member.members.get("__init__")
        if init is not None and _kind(init) == "function":
            params = ", ".join(
                str(p.name) if p.annotation is None else f"{p.name}: {p.annotation}"
                for p in init.parameters
                if p.name != "self"
            )
            return f"class {member.name}({bases})\n    def __init__({params})"
        return f"class {member.name}({bases})"
    return f"{member.name}"


def _sections(member) -> list[str]:  # noqa: ANN001
    docstring = member.docstring
    if docstring is None:
        return ["_No docstring._"]
    out: list[str] = []
    for section in docstring.parse("google"):
        kind = str(section.kind.value)
        if kind == "text":
            out.append(_prose(section.value))
        elif kind in {"parameters", "other parameters", "attributes"}:
            out.append(f"**{kind.capitalize()}**")
            out.append("")
            out.append("| Name | Type | Description |")
            out.append("|---|---|---|")
            for item in section.value:
                annotation = str(item.annotation) if item.annotation is not None else ""
                out.append(f"| `{item.name}` | `{annotation}` | {_cell(item.description)} |")
        elif kind == "raises":
            out.append("**Raises**")
            out.append("")
            out.append("| Exception | When |")
            out.append("|---|---|")
            for item in section.value:
                out.append(f"| `{item.annotation}` | {_cell(item.description)} |")
        elif kind == "returns":
            out.append("**Returns**")
            out.append("")
            for item in section.value:
                annotation = str(item.annotation) if item.annotation is not None else ""
                out.append(f"- `{annotation}` {_prose(item.description)}".rstrip())
        elif kind == "examples":
            out.append("**Example**")
            out.append("")
            for _, value in section.value:
                out.append("```python")
                out.append(str(value).strip())
                out.append("```")
        else:
            out.append(f"**{kind.capitalize()}**")
            out.append("")
            out.append(_prose(str(section.value)))
        out.append("")
    return out


def _prose(text: str) -> str:
    """Docstring prose as MDX: outside inline code, braces and angle brackets would be parsed
    as JSX, so they are escaped; inside a code span they are shown as written."""
    parts = re.split(r"(`[^`]*`)", text)
    for index, part in enumerate(parts):
        if part.startswith("`"):
            continue
        parts[index] = (
            part.replace("{", "&#123;")
            .replace("}", "&#125;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
    return "".join(parts)


def _cell(text: str) -> str:
    return _prose(text).replace("\n", " ").replace("|", "\\|")


def _page(member, module_path: str, name: str) -> str:  # noqa: ANN001
    summary = ""
    if member.docstring is not None:
        summary = member.docstring.value.strip().split("\n\n")[0].replace("\n", " ")
    summary = summary.replace('"', "'")
    where = ""
    try:
        where = f"{relative(Path(str(member.filepath)))}:{member.lineno}"
    except Exception:
        where = ""
    lines = [
        "---",
        f'title: "{name}"',
        f'description: "{summary or name}"',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
        f"`{module_path}.{name}` — {_kind(member)}" + (f", defined at `{where}`" if where else ""),
        "",
        "```python",
        _signature(member),
        "```",
        "",
        *_sections(member),
        "## Next",
        "",
        "- [Python API index](/reference/api/index).",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    return "\n".join(lines)


def render() -> dict[str, str]:
    """Every page to write, keyed by path relative to `API_DIR`."""
    package = _load()
    pages: dict[str, str] = {}
    index_rows: list[tuple[str, str, str, str]] = []
    for module_path, name in _public_names(package):
        member = _resolve(package, module_path, name)
        slug = _slug(module_path, name)
        pages[f"{slug}.mdx"] = _page(member, module_path, name)
        summary = ""
        if member.docstring is not None:
            summary = member.docstring.value.strip().split("\n")[0]
        index_rows.append((slug, f"{module_path}.{name}", _kind(member), _cell(summary)))
    lines = [
        "---",
        'title: "Python API"',
        'description: "Every frozen public name of the ctrlrun package and its extras, one '
        'page each, rendered from the docstrings."',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
        "The names below are the ones the specifications freeze: `ctrlrun.__all__`, the entry",
        "points of the extras, and `ctrlrun.verify.run`. Each page is rendered from the docstring;",
        "a name with no docstring fails a test, so every page has one.",
        "",
        "| Name | Kind | Summary |",
        "|---|---|---|",
    ]
    for slug, qualified, kind, summary in index_rows:
        lines.append(f"| [`{qualified}`](/reference/api/{slug}) | {kind} | {summary} |")
    lines += [
        "",
        "## Next",
        "",
        "- [CLI reference](/reference/cli).",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    pages["index.mdx"] = "\n".join(lines)
    return pages


def navigation_pages(pages: Iterable[str]) -> list[str]:
    slugs = sorted(p.removesuffix(".mdx") for p in pages if p != "index.mdx")
    return ["reference/api/index", *(f"reference/api/{slug}" for slug in slugs)]


def _docs_json_group(document: dict) -> dict | None:
    def walk(node):  # noqa: ANN001, ANN202
        if isinstance(node, dict):
            if node.get("group") == GROUP:
                return node
            for value in node.values():
                found = walk(value)
                if found is not None:
                    return found
        if isinstance(node, list):
            for item in node:
                found = walk(item)
                if found is not None:
                    return found
        return None

    return walk(document.get("navigation"))


def check(pages: dict[str, str]) -> list[str]:
    drift: list[str] = []
    for name, text in pages.items():
        target = API_DIR / name
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            drift.append(f"{relative(target)} differs from the docstrings; run --write")
    for existing in API_DIR.glob("*.mdx"):
        if existing.name not in pages:
            drift.append(f"{relative(existing)} is not a public name; remove it")
    document = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    group = _docs_json_group(document)
    if group is None:
        drift.append(f"docs.json has no '{GROUP}' group")
    elif group.get("pages") != navigation_pages(pages):
        drift.append(f"docs.json '{GROUP}' pages differ from the rendered set; run --write")
    return drift


def write(pages: dict[str, str]) -> None:
    API_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in pages.items():
        (API_DIR / name).write_text(text, encoding="utf-8")
    for existing in API_DIR.glob("*.mdx"):
        if existing.name not in pages:
            existing.unlink()
    document = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    group = _docs_json_group(document)
    if group is None:
        raise SystemExit(f"docs.json has no '{GROUP}' group to fill")
    group["pages"] = navigation_pages(pages)
    DOCS_JSON.write_text(
        json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    pages = render()
    if arguments.write:
        write(pages)
        print(f"wrote {len(pages)} pages under {relative(API_DIR)} and the docs.json group")
    if arguments.check or not arguments.write:
        drift = check(pages)
        for item in drift:
            print(f"DRIFT {item}")
        print(f"api reference: {len(pages)} pages, {len(drift)} drifted")
        return 0 if not drift else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
