"""Render the readiness block, the same in three places, from generated sources only.

The block is the first thing a stranger reads about whether CTRLRun can be run for real, so
every number in it comes from something that measures itself:

- the version and the dependency floor from `pyproject.toml`;
- the test count from `pytest --collect-only`, recorded in `docs/generated/readiness.json`;
- the soak's duration, actions and unattributed count from `research/soak/results/*.json`;
- what `ctrlrun verify` checks from the guarantee catalogue itself.

And it carries a **Not yet** list, inside the block and never below it: no external security
audit, no third-party review of the kernel, no sector packs. The honest half is why the first
half is believed. A line leaves only when the thing it names has become true, in its own pull
request, and `docs/CLAIMS.md` changes in the same one.

    python tools/docs_audit/render_readiness.py --write   # refresh, re-counting the suite
    python tools/docs_audit/render_readiness.py --check    # what CI runs

**The test count is a floor, not a snapshot.** `--check` fails when the suite has *fewer* tests
than the block claims, and passes when it has more: the suite only grows, and a number that had
to be regenerated by every pull request that added a test would be regenerated without being
read. `--write` records the count of the moment; the badge in the README is live.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

from _files import REPO_ROOT, relative

STATE = REPO_ROOT / "docs" / "generated" / "readiness.json"
GENERATED = REPO_ROOT / "docs" / "generated"
FILENAMES = {"readme": "readiness.readme.md", "mdx": "readiness.mdx", "full": "readiness.full.mdx"}
FORMATS = tuple(FILENAMES)
SOAK = REPO_ROOT / "research" / "soak" / "results"
CRITERION_DAYS = 7
_OPEN = re.compile(r"generated from the suite, pyproject and the soak \((?P<format>[a-z]+)\)")
_CLOSE = re.compile(r"end generated")

#: Stated here rather than counted, because each is a statement about what has **not** been
#: done and nothing in the repository can measure an absence. Removing one is its own pull
#: request, with the CLAIMS.md row that makes the new sentence true.
NOT_YET: tuple[tuple[str, str], ...] = (
    ("No external security audit.", "planned for v0.8 or v0.9"),
    ("No third-party review of the kernel.", "every review so far was run inside this project"),
    ("No sector packs.", "the policy templates are starting points, not a product"),
)


def _version() -> str:
    with (REPO_ROOT / "pyproject.toml").open("rb") as handle:
        return str(tomllib.load(handle)["project"]["version"])


def collected() -> int:
    """How many tests `pytest` collects right now."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    found = re.search(r"(\d+)\s+tests? collected", result.stdout)
    if found is None:
        raise SystemExit(f"could not read a test count from pytest:\n{result.stdout[-2000:]}")
    return int(found.group(1))


def soak() -> dict | None:
    """The most recent soak run, or `None` where none has been published."""
    files = sorted(SOAK.glob("*.json")) if SOAK.is_dir() else []
    return json.loads(files[-1].read_text(encoding="utf-8")) if files else None


def state() -> dict:
    return json.loads(STATE.read_text(encoding="utf-8")) if STATE.exists() else {}


def measure() -> dict:
    """Everything the block says, measured now."""
    run = soak()
    return {
        "version": _version(),
        "tests": collected(),
        "guarantees": _guarantees(),
        "soak": None
        if run is None
        else {
            "elapsed": run["elapsed_human"],
            "elapsed_seconds": run["elapsed_seconds"],
            "backend": run["backend"].split(" ")[0],
            "actions": run["actions"],
            "unexplained": run["unexplained"],
            "positive_control": run["positive_control_fired"],
        },
    }


def _guarantees() -> int:
    from ctrlrun.verify.guarantees import GUARANTEES

    return len(GUARANTEES)


def _lines(data: dict, *, full: bool) -> list[str]:
    version, tests, guarantees = data["version"], data["tests"], data["guarantees"]
    run = data["soak"]
    link = "https://pypi.org/project/ctrlrun/"

    def where(text: str, page: str) -> str:
        """`full` adds a Read-more link; the other formats carry the sentence alone.

        The soak line is the exception and links in every format: on the README and the docs
        home it is the one bullet a reader could quote as a stronger claim than it is, so the
        route to the page that qualifies it travels with it.
        """
        if full:
            return f"{text} [Read more](/{page})."
        if page == "production/soak":
            return f"{text} [What it does not establish](https://docs.ctrlrun.dev/{page})."
        return text

    lines = [
        f"- **Version {version}**, on [PyPI]({link}), Python 3.11 and later.",
        where(
            f"- **{tests:,} tests**, every version specified before it was written and every "
            "requirement mutation-tested.",
            "how-this-is-built",
        ),
        where(
            f"- **{guarantees} guarantees you can check in your own setup**, with `ctrlrun verify` "
            "against your policy, on your store's backend, in a scratch store it creates.",
            "security/verify-guarantees",
        ),
        where(
            "- **One host: a file.** SQLite, no server, no ops. **Many hosts: Postgres**, the same "
            "guarantees, graded by the same suite.",
            "production/postgres",
        ),
    ]
    if run is not None:
        lines.append(
            where(
                f"- **Soaked for {run['elapsed']} on {run['backend']}**: {run['actions']:,} actions, "
                f"{run['unexplained']} unattributed ambiguous outcomes"
                + (", positive control fired." if run["positive_control"] else ".")
                # The duration travels with the number, in every format. Without it the README
                # and the docs home carried "soaked" with no route to the page that says the
                # roadmap asks for a week -- the flattering half of a true sentence, on the two
                # surfaces most likely to be quoted.
                + " The roadmap asks for a week; that is not met.",
                "production/soak",
            )
        )
    else:
        lines.append("- **The soak has not been run for this version yet.**")
    lines += [
        where(
            "- **Each receipt carries the hash of the one before it**, so an alteration is detected "
            "and named.",
            "production/receipt-integrity",
        ),
        "- **Apache-2.0**, and the enforcement kernel stays open source. Releases carry PyPI "
        "provenance attestations from GitHub Actions.",
        "",
        "**Not yet:**",
        "",
    ]
    lines += [f"- {claim} ({why})" for claim, why in not_yet(data)]
    return lines


def not_yet(data: dict) -> tuple[tuple[str, str], ...]:
    """`NOT_YET`, plus the soak's week where the published run has not reached it.

    Derived rather than written down, for the same reason the page is: the day a week is
    actually run, a hard-coded line would keep saying it was not, and that failure is the
    flattering one.
    """
    run = data["soak"]
    if run is None:
        return NOT_YET
    if run["elapsed_seconds"] >= CRITERION_DAYS * 86_400 and run["unexplained"] == 0:
        return NOT_YET
    return (
        (
            "No soak of the length the roadmap asks for.",
            f"the criterion is a week of calendar time; the published run is {run['elapsed']}",
        ),
        *NOT_YET,
    )


def render(fmt: str, data: dict) -> str:
    body = _lines(data, full=fmt == "full")
    comment = f"generated from the suite, pyproject and the soak ({fmt}) — run the generator"
    open_marker = f"<!-- {comment} -->" if fmt == "readme" else "{/* " + comment + " */}"
    close_marker = "<!-- end generated -->" if fmt == "readme" else "{/* end generated */}"
    return "\n".join([open_marker, *body, close_marker]) + "\n"


def marker_blocks(text: str) -> list[tuple[int, str, str]]:
    lines = text.splitlines()
    blocks: list[tuple[int, str, str]] = []
    index = 0
    while index < len(lines):
        opened = _OPEN.search(lines[index])
        if opened is None:
            index += 1
            continue
        start, fmt = index, opened.group("format")
        index += 1
        while index < len(lines) and not _CLOSE.search(lines[index]):
            index += 1
        if index >= len(lines):
            blocks.append((start + 1, fmt, ""))
            break
        blocks.append((start + 1, fmt, "\n".join(lines[start : index + 1]) + "\n"))
        index += 1
    return blocks


def check(data: dict, pages: list[Path] | None = None) -> list[str]:
    drift: list[str] = []
    recorded = state()
    if not recorded:
        return [f"{relative(STATE)} is missing; run --write"]
    current = data["tests"]
    if current < recorded["tests"]:
        drift.append(
            f"the block claims {recorded['tests']:,} tests and the suite collects {current:,}; "
            "run --write"
        )
    for key in ("version", "guarantees", "soak"):
        if recorded.get(key) != data.get(key):
            drift.append(f"{key} changed since the block was generated; run --write")
    for fmt in FORMATS:
        target = GENERATED / FILENAMES[fmt]
        expected = render(fmt, recorded)
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            drift.append(f"{relative(target)} differs from the generator; run --write")
    if pages is None:
        from _files import documents

        pages = documents(patterns=("README.md", "docs/**/*.md", "docs/**/*.mdx"))
    for page in pages:
        if page.parent == GENERATED:
            continue
        for line, fmt, embedded in marker_blocks(page.read_text(encoding="utf-8")):
            if fmt not in FORMATS:
                drift.append(f"{relative(page)}:{line}: unknown readiness format {fmt!r}")
            elif embedded != render(fmt, recorded):
                drift.append(f"{relative(page)}:{line}: readiness block differs; paste it fresh")
    return drift


def write(data: dict) -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    for fmt in FORMATS:
        (GENERATED / FILENAMES[fmt]).write_text(render(fmt, data), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("format", nargs="?", choices=FORMATS)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    if arguments.format:
        sys.stdout.write(render(arguments.format, state() or measure()))
        return 0
    data = measure()
    if arguments.write:
        write(data)
        print(f"readiness: {data['tests']:,} tests, version {data['version']}, written")
    if arguments.check or not arguments.write:
        drift = check(data)
        for item in drift:
            print(f"DRIFT {item}")
        print(f"readiness: {len(drift)} drifted")
        return 0 if not drift else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
