"""Render the receipt and event schemas and the error hierarchy from the code.

Three pages, each a marker-headed render that `--check` refuses when it has drifted:

- `docs/reference/receipt-and-event-schemas.mdx` from the `Receipt` and `Event` dataclasses and
  the `EventType` enum;
- `docs/reference/errors.mdx` from `ctrlrun.errors`, every class with its base and the first
  line of its docstring.

    python tools/docs_audit/render_schemas.py --write
    python tools/docs_audit/render_schemas.py --check
"""

from __future__ import annotations

import argparse
import dataclasses
import inspect
import sys
import typing
from pathlib import Path

from _files import REPO_ROOT, relative

SCHEMAS = REPO_ROOT / "docs" / "reference" / "receipt-and-event-schemas.mdx"
ERRORS = REPO_ROOT / "docs" / "reference" / "errors.mdx"
MARKER = "generated by tools/docs_audit/render_schemas.py from the code — edit the dataclasses and docstrings, never this page"


def _type_name(annotation: object) -> str:
    text = (
        annotation
        if isinstance(annotation, str)
        else getattr(annotation, "__name__", str(annotation))
    )
    return text.replace("typing.", "")


def _fields(cls: type) -> list[tuple[str, str, str]]:
    hints = typing.get_type_hints(cls, include_extras=False)
    rows: list[tuple[str, str, str]] = []
    for item in dataclasses.fields(cls):
        default = ""
        if item.default is not dataclasses.MISSING:
            default = repr(item.default)
        elif item.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            default = "(empty)"
        rows.append((item.name, _type_name(hints.get(item.name, item.type)), default))
    return rows


def _table(rows: list[tuple[str, str, str]]) -> list[str]:
    lines = ["| Field | Type | Default |", "|---|---|---|"]
    for name, kind, default in rows:
        lines.append(
            f"| `{name}` | `{kind}` | {('`' + default + '`') if default else 'required'} |"
        )
    return lines


def render_schemas() -> str:
    from ctrlrun import Event, Receipt
    from ctrlrun.receipt import EventType, ReceiptResult

    lines = [
        "---",
        'title: "Receipt and event schemas"',
        'description: "Every field of a CTRLRun receipt (ctrlrun.receipt/v3) and of an event, and every event type, rendered from the dataclasses that write them."',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
        "A receipt is one executed action; an event is one step on the way. Both are written to the",
        "store, appended to `.ctrlrun/receipts.jsonl` and `.ctrlrun/events.jsonl` as one JSON object",
        "per line, and exported to any sink installed. Every enum renders by value, so a reader that",
        "never imported CTRLRun can read the evidence.",
        "",
        "## Receipt",
        "",
        "`ctrlrun.receipt/v3`. `seq`, `prev_hash` and `hash` are the chain; `policy_hash` and",
        "`policy_version` say which policy decided the action; `controls` are the registry ids the",
        "action and its matched rule cite.",
        "",
        *_table(_fields(Receipt)),
        "",
        "### Result",
        "",
        "| Value | Meaning |",
        "|---|---|",
    ]
    for member in ReceiptResult:
        lines.append(f"| `{member.value}` | {_result_meaning(member.name)} |")
    lines += [
        "",
        "## Event",
        "",
        *_table(_fields(Event)),
        "",
        "### Event types",
        "",
        "In the order the specification introduced them. The five authority types appear only in a",
        "configuration with an `authority:` section.",
        "",
        "| Type |",
        "|---|",
    ]
    for member in EventType:
        lines.append(f"| `{member.value}` |")
    lines += [
        "",
        "## Next",
        "",
        "- [Receipts and evidence](/concepts/receipts-and-evidence): what a receipt is for.",
        "- [The receipt chain](/security/receipt-chain): what `seq`, `prev_hash` and `hash` detect.",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    return "\n".join(lines)


def _result_meaning(name: str) -> str:
    return {
        "COMMITTED": "the executor returned; the remote did it",
        "FAILED": "the executor raised `NotExecuted`; the remote provably did nothing",
        "AMBIGUOUS": "the executor raised anything else, timed out, or never returned; nobody knows",
        "BLOCKED": "refused before the executor ran: denied, mismatched approval, duplicate or ambiguous effect",
        "OBSERVED": "observe mode: executed, with what enforce mode would have done recorded in `would_have`",
        "SUSPENDED": "the executor raised `Suspended`; the reservation is held for a continuation",
    }.get(name, "")


def render_errors() -> str:
    from ctrlrun import errors

    classes = [
        obj
        for _, obj in inspect.getmembers(errors, inspect.isclass)
        if obj.__module__ == errors.__name__ and issubclass(obj, Exception)
    ]
    order = {name: index for index, name in enumerate(_source_order(errors))}
    classes.sort(key=lambda cls: order.get(cls.__name__, len(order)))
    lines = [
        "---",
        'title: "Errors"',
        'description: "The closed set of CTRLRun exceptions: ActionDenied, ApprovalRequired, ApprovalMismatch, DuplicateEffect, AmbiguousEffect, NotExecuted and the rest, each with its base class and when it is raised."',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
        "Every refusal is an exception of its own, raised as itself before the executor runs, so an",
        "agent loop can tell them apart with `except`. All of them derive from `CTRLRunError`; the",
        "set is closed by the specification and a new one is a specification amendment first.",
        "",
        "| Exception | Base | Raised when |",
        "|---|---|---|",
    ]
    for cls in classes:
        base = cls.__mro__[1].__name__
        first = (inspect.getdoc(cls) or "").split("\n\n")[0].replace("\n", " ")
        lines.append(f"| `{cls.__name__}` | `{base}` | {_prose(first)} |")
    lines += ["", "## Each one", ""]
    for cls in classes:
        lines.append(f"### {cls.__name__}")
        lines.append("")
        lines.append(_prose(inspect.getdoc(cls) or ""))
        lines.append("")
    lines += [
        "## Next",
        "",
        "- [Fail closed](/concepts/fail-closed): the table of what is refused, and where.",
        "- [Outcomes and AMBIGUOUS](/concepts/outcomes-and-ambiguous): `NotExecuted` and why it is the dangerous one.",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    return "\n".join(lines)


def _prose(text: str) -> str:
    """Outside inline code, braces and angle brackets would be parsed as JSX."""
    import re

    parts = re.split(r"(`[^`]*`)", text)
    for index, part in enumerate(parts):
        if not part.startswith("`"):
            parts[index] = (
                part.replace("{", "&#123;")
                .replace("}", "&#125;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
    return "".join(parts)


def _source_order(module: object) -> list[str]:
    import re

    source = Path(inspect.getsourcefile(module) or "").read_text(encoding="utf-8")
    return re.findall(r"^class (\w+)", source, re.M)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    status = 0
    for target, text in ((SCHEMAS, render_schemas()), (ERRORS, render_errors())):
        if arguments.write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            print(f"wrote {relative(target)}")
        if arguments.check or not arguments.write:
            if not target.exists() or target.read_text(encoding="utf-8") != text:
                print(f"DRIFT {relative(target)} differs from the code; run --write")
                status = 1
            else:
                print(f"schemas: {relative(target)} matches")
    return status


if __name__ == "__main__":
    sys.exit(main())
