"""Render the framework-probe study page from the published results, and refuse a hand edit.

`docs/study/does-your-framework-double-execute.mdx` is a **render**, never written by hand:
its table comes from `research/framework-probe/results/*.json`, which the maintainer publishes
by committing a run. Until one exists the page says so, in those words, and lists no framework.

    python tools/docs_audit/render_probe.py --write
    python tools/docs_audit/render_probe.py --check

A framework whose adapter was never executed is not in the results file and therefore not on the
page: the one way a row appears is that the harness produced it.

The page lives under `docs/study/` and not `docs/research/` because two release guards refuse
**any** path segment named `research` in a distribution, which is how the harness at the
repository root is kept out of the wheel. Renaming one page is cheaper than making a
release-critical rule subtler.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from _files import REPO_ROOT, relative

RESULTS = REPO_ROOT / "research" / "framework-probe" / "results"
TARGET = REPO_ROOT / "docs" / "study" / "does-your-framework-double-execute.mdx"
MARKER = (
    "generated by tools/docs_audit/render_probe.py from "
    "research/framework-probe/results/ — publish a run, do not edit this page"
)
NO_RESULTS = "No published results yet."

#: The scenarios the harness runs, in the order the page reads them.
SCENARIOS: tuple[tuple[str, str], ...] = (
    ("double-refund", "Double execution"),
    ("approval-mutation", "Approval mutation"),
)

#: SPEC-v0.4 §7.3's fairness rules, quoted because the table carries other projects' names.
FAIRNESS: tuple[str, ...] = (
    "The same fake remote for every framework, a fresh instance per run.",
    "The same scenario text: prompt, tool name, description and schema byte-identical wherever the framework's API admits it.",
    "Framework defaults. No retry setting changed, no timeout tuned, no guard added.",
    "At most one configuration change per framework, only where the scenario cannot run without it, and it appears in the table's own column.",
    "The version is read at runtime from the installed distribution, never typed by hand.",
    "The table reports behaviour, not quality.",
)


def latest() -> tuple[Path, dict] | None:
    """The most recent published results file, or `None` where none exists."""
    files = sorted(RESULTS.glob("*.json"))
    if not files:
        return None
    newest = files[-1]
    return newest, json.loads(newest.read_text(encoding="utf-8"))


def unrun(entry: dict) -> bool:
    """Was this adapter executed at all?

    An entry whose notes begin `skipped:` is an adapter the harness never ran, because the
    framework was not installed. It is **not a measurement** and must never reach the table:
    the probe's README says these frameworks "remain unexecuted in every sense", and a row that
    read `error` beside a version-less framework would be a finding about it.
    """
    return str(entry.get("notes", "")).startswith("skipped:")


def _rows(document: dict) -> tuple[list[tuple[str, str, dict[str, dict]]], dict[str, str]]:
    """The measured frameworks, and the ones the harness never ran with the reason."""
    by_framework: dict[str, dict[str, dict]] = {}
    versions: dict[str, str] = {}
    skipped: dict[str, str] = {}
    for entry in document["results"]:
        if unrun(entry):
            skipped[entry["framework"]] = str(entry["notes"]).removeprefix("skipped:").strip()
            continue
        by_framework.setdefault(entry["framework"], {})[entry["scenario"]] = entry
        versions[entry["framework"]] = entry.get("version", "")
    measured = [
        (name, versions[name], scenarios)
        for name, scenarios in by_framework.items()
        if name not in skipped
    ]
    return measured, skipped


def _cell(entry: dict | None) -> str:
    if entry is None:
        return "not run"
    outcome = f"`{entry['outcome']}`"
    deviation = entry.get("config_deviation")
    return outcome if not deviation else f"{outcome} ({deviation})"


def render() -> str:
    found = latest()
    lines = [
        "---",
        'title: "Does your framework double-execute?"',
        'description: "What agent frameworks do when a remote commits and the reply is lost, '
        'measured with one harness, the same fake remote and framework defaults."',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
        "When a remote commits a refund and the reply is lost, what does an agent framework do?",
        "This page is the measurement, not an argument: one harness, one fake remote, framework",
        "defaults, and a table rendered from the run's own JSON.",
        "",
        "**It reports behaviour, not quality.** None of these projects claims to solve duplicate",
        "execution, and none is doing anything its documentation does not describe. The finding is",
        "about what an agent stack does *without* an effect-level guard.",
        "",
    ]
    if found is None:
        lines += [
            "## " + NO_RESULTS,
            "",
            "The harness exists and the fairness rules below are in force; nothing has been",
            "published. A row appears here only when a run has been committed to",
            "`research/framework-probe/results/`, so this page can never describe a framework whose",
            "adapter was not executed.",
            "",
        ]
    else:
        path, document = found
        measured, skipped = _rows(document)
        lines += [
            f"## What the run of {document['run_at'][:10]} found",
            "",
            "| Framework | Version | " + " | ".join(label for _, label in SCENARIOS) + " |",
            "|---|---|" + "---|" * len(SCENARIOS),
        ]
        for name, version, scenarios in measured:
            cells = " | ".join(_cell(scenarios.get(key)) for key, _ in SCENARIOS)
            lines.append(f"| {name} | {version or '—'} | {cells} |")
        lines.append("")
        for name, _version, scenarios in measured:
            for key, label in SCENARIOS:
                entry = scenarios.get(key)
                if entry and entry.get("notes"):
                    lines.append(f"- **{name}, {label.lower()}**: {entry['notes']}")
        lines += [
            "",
            f"Run on {document['run_at'][:10]} against `{document['remote']}` on Python "
            f"{document['python']}. The file is "
            f"[`{relative(path)}`](https://github.com/CTRLRun/ctrlrun/blob/main/{relative(path)}).",
            "",
            "**Read the approval-mutation column carefully.** `executed_once` there does not mean",
            "the scenario was handled well: it means the *mutated* action, the refund the human",
            "never approved, reached the remote and committed. Every row shows it, the stubs",
            "included, because nothing in these stacks binds a human's approval to the exact action",
            "that then runs. `outcome` is a closed set with no value for *the mutation landed*,",
            "which is why that is said here rather than in a cell.",
            "",
            "**The double-execution column is the finding.** The two stub rows are the control: a",
            "harness that reported `executed_twice` unconditionally would have said the same about",
            "both of them.",
            "",
        ]
        if skipped:
            lines += [
                "### Not run",
                "",
                "An adapter exists for each of these and **was never executed**, so this page says",
                "nothing about them. They are listed by name rather than left out, because a reader",
                "who knows the adapter exists should not have to wonder what happened to it.",
                "",
            ]
            lines += [f"- **{name}**: {reason}." for name, reason in sorted(skipped.items())]
            lines.append("")
    lines += [
        "## The fairness rules",
        "",
        "Normative, because the table carries other projects' names.",
        "",
    ]
    lines += [f"{index}. {rule}" for index, rule in enumerate(FAIRNESS, start=1)]
    lines += [
        "",
        "## Run it yourself",
        "",
        "The harness is in the repository, outside the package, and is never shipped in a wheel.",
        "It needs the network, real API keys and a budget, which is why its results are published",
        "by hand rather than by CI.",
        "",
        "```bash",
        "python research/framework-probe/run.py --help",
        "```",
        "",
        "[`research/framework-probe/README.md`](https://github.com/CTRLRun/ctrlrun/blob/main/research/framework-probe/README.md)",
        "has the scenarios, the fake remote, each framework's documented defaults with the date",
        "read, and what a run does not establish.",
        "",
        "## Next",
        "",
        "- [Outcomes and AMBIGUOUS](/concepts/outcomes-and-ambiguous): what a lost reply is, and why a retry is refused.",
        "- [Effect keys](/concepts/effect-keys): the guard the frameworks above are running without.",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    text = render()
    if arguments.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text, encoding="utf-8")
        print(f"wrote {relative(TARGET)}")
    if arguments.check or not arguments.write:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"DRIFT {relative(TARGET)} differs from the published results; run --write")
            return 1
        print(f"probe page: {relative(TARGET)} matches the published results")
    return 0


if __name__ == "__main__":
    sys.exit(main())
