#!/usr/bin/env python
"""Render `snippets/how-diagram.jsx`, the how-it-works diagram on the home page.

The drawing is two SVGs: seven stages on one spine for wide screens, the same seven stacked for
narrow ones. CSS swaps them at 820px -- one SVG scaled from a 1200-wide viewBox down to a phone
renders its 11px labels at 4px, which is not a diagram any more.

Every coordinate here is computed from the stage list rather than typed. Adding a stage, or
making a caption longer, moves the connectors, the nodes, the divider and the box that encloses
them together; by hand that is how a box ends up one stage short of the arrow leaving it.

The output is checked in. Run this after editing STAGES, RULES or the strips, then reload the
page: `python3 scripts/render-how-diagram.py`.
"""

from pathlib import Path

# (number, name, gloss). The gloss shares a 144px node with the name, so it stays under about
# 20 characters -- SVG text does not wrap, it just runs out of the box.
STAGES: list[tuple[str, str, str]] = [
    ("1", "Normalize", "one action, one id"),
    ("2", "Decide", "allow / ask / block"),
    ("3", "Approve", "bound to this action"),
    ("4", "Reserve", "claimed once"),
    ("5", "Execute", "your code runs"),
    ("6", "Resolve", "unknown is not failed"),
    ("7", "Record", "a receipt either way"),
]

# What the boundary refuses. One line each on wide, two on narrow.
RULES: list[tuple[str, str]] = [
    ("No rule for it", "The action is blocked. Silence is never permission."),
    ("Arguments changed after sign-off", "The old approval is void. A person signs again."),
    ("Outcome unknown", "No retry until a person resolves it. Nothing runs twice on a guess."),
]
NARROW_RULES: list[tuple[str, list[str]]] = [
    ("No rule for it", ["The action is blocked.", "Silence is never permission."]),
    ("Arguments changed after sign-off", ["The old approval is void.", "A person signs again."]),
    ("Outcome unknown", ["No retry until a person resolves it.", "Nothing runs twice on a guess."]),
]

# The two ends name what the reader already has, in the vocabulary the home page uses.
# No worked example: the process is the point, and a refund makes it look like a payments tool.
TOP = (
    "YOUR AGENTS, TOOLS AND WORKFLOWS",
    "An action is about to run.",
    "Any model, any framework. Existing code stays as it is.",
)
BOT = ("YOUR SYSTEMS", "The action arrives already checked.")
BOT_NOTE = "Allowed by your rules, approved where you require it, and never run twice."
BOX_LABEL = "ctrlrun · THE EXECUTION BOUNDARY"

# The commercial band that used to sit on the boundary is gone. The tiers have their own
# section directly below the diagram, and the drawing repeated it a screen early.

DESC = (
    "An action leaves the agents, tools and workflows you already run. Inside ctrlrun it is "
    "normalized into one action, decided against your rules, held for approval, reserved so it "
    "cannot run twice, executed, resolved and recorded. Only then does it reach your systems. "
    "An action with no rule is blocked, changed arguments void the approval, and an unknown "
    "outcome is never retried."
)

HEADER = """// Generated by scripts/render-how-diagram.py -- edit that, not this.
//
// It lives in a snippet rather than inline in index.mdx because the MDX pipeline strips SVG
// <text> (and bare <strong>) from the page: the shapes survive, the labels do not. Snippets are
// real modules, so the whole drawing arrives intact.
"""


def esc(text: str) -> str:
    """Escape for JSX text content. Quotes are safe; braces and angle brackets are not."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def down_arrow(x: int, y1: int, y2: int) -> list[str]:
    """A shaft plus a solid head whose tip lands exactly on y2."""
    return [
        f'<path className="cr-dia-arrow" d="M{x} {y1}V{y2 - 7}" />',
        f'<path className="cr-dia-head" d="M{x - 5} {y2 - 8}h10L{x} {y2}Z" />',
    ]


def wide() -> str:
    """1200x416: the strip we do not own, the box we do, the strip we do not own."""
    width, pad = 1200, 24
    box_y, box_h = 92, 230
    node_y, node_h, node_w, step = 138, 86, 144, 168
    out = [
        '<rect className="cr-dia-strip" x="1" y="1" width="1198" height="54" rx="6" />',
        f'<text className="cr-dia-label" x="{pad}" y="33">{esc(TOP[0])}</text>',
        f'<text className="cr-dia-claim" x="390" y="34">{esc(TOP[1])}</text>',
        f'<text className="cr-dia-note" x="628" y="34">{esc(TOP[2])}</text>',
        *down_arrow(600, 56, 90),
        f'<rect className="cr-dia-box" x="1" y="{box_y}" width="1198" height="{box_h}" rx="6" />',
        f'<text className="cr-dia-label" x="{pad}" y="122">{esc(BOX_LABEL)}</text>',
    ]
    for i, (num, name, gloss) in enumerate(STAGES):
        x = pad + i * step
        out += [
            f'<rect className="cr-dia-node" x="{x}" y="{node_y}" width="{node_w}"'
            f' height="{node_h}" rx="5" />',
            f'<text className="cr-dia-num" x="{x + 13}" y="{node_y + 24}">{num}</text>',
            f'<text className="cr-dia-name" x="{x + 13}" y="{node_y + 48}">{esc(name)}</text>',
            f'<text className="cr-dia-gloss" x="{x + 13}" y="{node_y + 68}">{esc(gloss)}</text>',
        ]
        if i < len(STAGES) - 1:
            mid, end = node_y + node_h // 2, x + node_w
            out += [
                f'<path className="cr-dia-arrow" d="M{end + 5} {mid}h11" />',
                f'<path className="cr-dia-head" d="M{end + 15} {mid - 4.5}l7 4.5-7 4.5Z" />',
            ]
    out.append(f'<path className="cr-dia-div" d="M{pad} 252H{width - pad}" />')
    col = (width - 2 * pad - 64) // 3
    for i, (head, note) in enumerate(RULES):
        x = pad + i * (col + 32)
        out += [
            f'<text className="cr-dia-rule" x="{x}" y="278">{esc(head)}</text>',
            f'<text className="cr-dia-rule-note" x="{x}" y="298">{esc(note)}</text>',
        ]
    bottom = box_y + box_h
    strip_y = bottom + 40
    out += down_arrow(600, bottom + 2, strip_y - 2)
    out += [
        f'<rect className="cr-dia-strip" x="1" y="{strip_y}" width="1198" height="54" rx="6" />',
        f'<text className="cr-dia-label" x="{pad}" y="{strip_y + 32}">{esc(BOT[0])}</text>',
        f'<text className="cr-dia-claim" x="252" y="{strip_y + 33}">{esc(BOT[1])}</text>',
        f'<text className="cr-dia-note" x="560" y="{strip_y + 33}">{esc(BOT_NOTE)}</text>',
    ]
    total = strip_y + 54 + 2
    body = "\n      ".join(out)
    return (
        f'    <svg className="cr-diagram cr-dia-wide" viewBox="0 0 1200 {total}" role="img"\n'
        '      aria-labelledby="cr-dia-t cr-dia-d" preserveAspectRatio="xMidYMid meet">\n'
        '      <title id="cr-dia-t">How ctrlrun works</title>\n'
        f'      <desc id="cr-dia-d">{esc(DESC)}</desc>\n      {body}\n    </svg>\n'
    )


def narrow() -> str:
    """360 wide, stacked: the same spine turned on its side. It carries its own title and
    description because below the swap it is the only diagram in the page -- the wide one is
    display:none, and a display:none sibling describes nothing."""
    width, pad = 360, 16
    box_y = 104
    row_y, row_h, row_step = 142, 34, 42
    rows_bottom = row_y + (len(STAGES) - 1) * row_step + row_h
    head = [
        '<rect className="cr-dia-strip" x="1" y="1" width="358" height="76" rx="6" />',
        f'<text className="cr-dia-label" x="{pad}" y="25">{esc(TOP[0])}</text>',
        f'<text className="cr-dia-claim" x="{pad}" y="47">{esc(TOP[1])}</text>',
        f'<text className="cr-dia-note" x="{pad}" y="66">{esc(TOP[2])}</text>',
        *down_arrow(180, 78, 102),
    ]
    body = [
        f'<text className="cr-dia-label" x="{pad}" y="130">{esc(BOX_LABEL)}</text>',
        f'<path className="cr-dia-spine" d="M{pad + 12} {row_y + 8}V{rows_bottom - 8}" />',
    ]
    for i, (num, name, gloss) in enumerate(STAGES):
        y = row_y + i * row_step
        body += [
            f'<rect className="cr-dia-node" x="{pad + 12}" y="{y}" width="{width - pad - 28}"'
            f' height="{row_h}" rx="4" />',
            f'<text className="cr-dia-num" x="{pad + 24}" y="{y + 22}">{num}</text>',
            f'<text className="cr-dia-name" x="{pad + 42}" y="{y + 22}">{esc(name)}</text>',
            f'<text className="cr-dia-gloss" x="{pad + 140}" y="{y + 22}">{esc(gloss)}</text>',
        ]
    divider = rows_bottom + 18
    body.append(f'<path className="cr-dia-div" d="M{pad + 12} {divider}H{width - pad}" />')
    y = divider + 24
    for rule, lines in NARROW_RULES:
        body.append(f'<text className="cr-dia-rule" x="{pad + 12}" y="{y}">{esc(rule)}</text>')
        for j, line in enumerate(lines):
            body.append(
                f'<text className="cr-dia-rule-note" x="{pad + 12}"'
                f' y="{y + 18 + j * 16}">{esc(line)}</text>'
            )
        y += 18 + 16 * len(lines) + 14
    box_h = y - 22 - box_y
    bottom = box_y + box_h
    strip_y = bottom + 30
    tail = [
        *down_arrow(180, bottom + 2, strip_y - 2),
        f'<rect className="cr-dia-strip" x="1" y="{strip_y}" width="358" height="76" rx="6" />',
        f'<text className="cr-dia-label" x="{pad}" y="{strip_y + 24}">{esc(BOT[0])}</text>',
        f'<text className="cr-dia-claim" x="{pad}" y="{strip_y + 46}">{esc(BOT[1])}</text>',
        f'<text className="cr-dia-note" x="{pad}" y="{strip_y + 65}">Allowed by your rules,'
        " approved where you require it.</text>",
    ]
    box = f'<rect className="cr-dia-box" x="1" y="{box_y}" width="358" height="{box_h}" rx="6" />'
    total = strip_y + 76 + 2
    joined = "\n      ".join([*head, box, *body, *tail])
    return (
        f'    <svg className="cr-diagram cr-dia-narrow" viewBox="0 0 360 {total}" role="img"\n'
        '      aria-labelledby="cr-dia-tn cr-dia-dn" preserveAspectRatio="xMidYMid meet">\n'
        '      <title id="cr-dia-tn">How ctrlrun works</title>\n'
        f'      <desc id="cr-dia-dn">{esc(DESC)}</desc>\n'
        f"      {joined}\n    </svg>\n"
    )


def render() -> str:
    return f"{HEADER}export const HowDiagram = () => (\n  <>\n{wide()}{narrow()}  </>\n);\n"


def main() -> None:
    target = Path(__file__).resolve().parent.parent / "snippets" / "how-diagram.jsx"
    target.write_text(render(), encoding="utf-8")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
